---
- hosts: all
  sudo: yes
  gather_facts: no

  tasks:
    - name: update apt database
      apt: update_cache=yes

    - name: setup some basic packages
      apt: state=latest name={{item}}
      with_items:
        - build-essential
        - tmux
        - git
        - vim



    - name: install apache + php5 + modules
      apt: state=latest name={{item}}
      with_items:
        - apache2
        - libapache2-mod-php5
        - php5-sqlite
        - php5-curl
      notify:
        - restart apache

    - name: disable apache's default site
      file: state=absent path=/etc/apache2/sites-enabled/000-default
      notify: restart apache

    - name: symlink apache config
      file: state=link src=/vagrant/provisioning/apache-vhost.conf dest=/etc/apache2/sites-enabled/sp-enduser
      notify: restart apache

    - name: make php report errors to the browser
      lineinfile:
        dest: /etc/php5/apache2/php.ini
        line: display_errors = On
        regexp: ^display_errors =
      notify: restart apache



    - name: install composer
      command: "/bin/bash -c 'curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin' creates=/usr/local/bin/composer"

    - name: rename composer binary
      command: /bin/mv /usr/local/bin/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer



    - name: copy the prepared settings.php file
      command: cp /vagrant/provisioning/settings.php /vagrant/settings.php creates=/vagrant/settings.php

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
